---
version: '2'

services:
  wsfschedule:
    build: .
    container_name: wsfschedule
    image: oaklabs/app-wsfschedule:latest
    network_mode: host
    privileged: true
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      # - ./src:/data/oak/app/src
    # environment:
    #   NODE_ENV: 'development'

  lights:
    container_name: lights
    image: oaklabs/lights:2.0.0-rc2
    privileged: true
    network_mode: host
    devices:
      - /dev/bus/usb
    volumes:
      - /run/udev:/run/udev
  api:
    container_name: api
    image: oaklabs/oakos-api:1.5.1
    network_mode: host
    privileged: true
    volumes_from:
      - lights
